Document: pyduin
Title: Debian pyduin Manual
Author: <insert document author here>
Abstract: This manual describes what pyduin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyduin/pyduin.sgml.gz

Format: postscript
Files: /usr/share/doc/pyduin/pyduin.ps.gz

Format: text
Files: /usr/share/doc/pyduin/pyduin.text.gz

Format: HTML
Index: /usr/share/doc/pyduin/html/index.html
Files: /usr/share/doc/pyduin/html/*.html
